# Generated by Django 2.0.7 on 2019-02-20 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='conversation',
            old_name='query',
            new_name='dose',
        ),
        migrations.RenameField(
            model_name='conversation',
            old_name='response',
            new_name='precautions',
        ),
        migrations.AddField(
            model_name='conversation',
            name='medicine',
            field=models.CharField(default='SOME STRING', max_length=100),
        ),
        migrations.AddField(
            model_name='conversation',
            name='symptoms',
            field=models.CharField(default='SOME STRING', max_length=100),
        ),
    ]
