# Generated by Django 2.0.7 on 2019-02-27 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatapp', '0002_auto_20190220_1014'),
    ]

    operations = [
        migrations.CreateModel(
            name='suggestions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input', models.CharField(default='SOME STRING', max_length=100)),
                ('output', models.TextField()),
            ],
        ),
    ]
